baseURL = "http://www.annexrecipes.com/"
languageCode = "en-us"
title = "Annex's Recipe Book"
theme = "cuisine-book"

[params]
  author = "Alexander Norris"
  description = "Recipes for friends and family of Annex"


[deployment]
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "annexrecipes"

URL = "gs://www.annexrecipes.com"

